### ISSUE TITLE
Create qr code service action for azure blobs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-qr-code#11]
In the gdocs2md implementation (and potentially the word2md), it might not possible to decode the inline images on time due to time and memory constraints. in such cases, a dedicated action should be invoked to augment the missing data:

- takes an url and returns a json containing the qrCode of the image (or some error information if the code couldn't be extracted)
- if the url is a helix azure blob url, it updates it's metadata with the result
- if the metadata already contain the QR code, it should not be updated again (since the blob name is a content hash and should remain stable)

Example metadata:

```
$ curl -sD- "https://hlx.blob.core.windows.net/external/4a6a05133a88e864c859ac9757b411e46220572f?comp=metadata"
HTTP/1.1 200 OK
Content-Length: 0
Last-Modified: Tue, 12 May 2020 08:16:00 GMT
ETag: "0x8D7F64CB4B0CD86"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: e68637d5-701e-0067-7fff-284208000000
x-ms-version: 2014-02-14
x-ms-meta-name: {"qrCode":"https://www.youtube.com/watch?v=m7atGkba-Z8"}
Date: Wed, 13 May 2020 08:22:59 GMT
```

The format of the metadata is not specified by [set blob metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata).
We choose to use a JSON string of a metadata object.

Something like:

```
POST http://adobeioruntime.net/helix/helix-services/qr-code?url=https://hlx.blob.core.windows.net/external/4a6a05133a88e864c859ac9757b411e46220572f

200 OK
content-type: application/json

{
  data: {"qrCode":"https://www.youtube.com/watch?v=m7atGkba-Z8"}
}
```

etc....

**Comment by stefan-guggisberg** [comment]
Alternative approach: implement an Azure Function which runs on every upload and extracts/updates meta data (e.g. qrCode).

**Comment by davidnuescheler** [comment]
i would rather not start to distribute our code into multiple runtime environments at this stage... (at least for the foreseeable future)

also, this may or may not be related, but i am having a broad range of issues that manifest as `400` and gets converted into `502` on helix-cli and `504` in runtime when new images are added to a google doc.

if this is related, i would suggest to disable the qr code extraction until we find a reliable solution.

**Comment by tripodsan** [comment]
> also, this may or may not be related, but i am having a broad range of issues that manifest as `400` and gets converted into `502` on helix-cli and `504` in runtime when new images are added to a google doc.
> 
> if this is related, i would suggest to disable the qr code extraction until we find a reliable solution.

no, it's not related.... the problem is: https://github.com/adobe/helix-documents-support/issues/8

**Comment by stefan-guggisberg** [comment]
After a discussion with @davidnuescheler I think we can close this issue for now and reconsider it later should there really be a problem with the current approach. Adding yet another action and triggering even more activations per request (we've already been hitting runtime limits) seems overkill at this point. The guards to prevent OOM errors we have in place (size and dimension limits (https://github.com/adobe/helix-documents-support/issues/17)) should be sufficient.
